# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
Z = np.zeros((10,10))
print(f"{Z.size * Z.itemsize} bytes")

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a = np.zeros(10)
a[5] = 1
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
a = np.arange(10,50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.random((3,3,3))

array([[[0.82801189, 0.38249366, 0.85819206],
        [0.19158309, 0.87170248, 0.81232072],
        [0.94032577, 0.36721291, 0.65153153]],

       [[0.51700998, 0.10802527, 0.77529207],
        [0.57699436, 0.71792734, 0.15670943],
        [0.91540851, 0.16559787, 0.47854506]],

       [[0.26918526, 0.07706928, 0.02637372],
        [0.70365629, 0.64076829, 0.75576478],
        [0.02852321, 0.68701887, 0.53702217]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
a = np.random.random((10,10))
print(a.max(), a.min())

0.9957685820752292 0.019456857190751742


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
np.random.random(30).mean()

0.4661135830940682

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
a = np.ones((5,5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
a = np.ones((5,5))
np.pad(a,(1,1))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
a = np.zeros((8,8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
a = np.array([[0,1],[1,0]])
np.tile(a,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
a = np.random.random((5,5))

(a - a.mean()) / ((a.max()) - (a.min()))

array([[-5.36344522e-01,  5.73918713e-02, -4.09860965e-01,
        -2.05127613e-04,  1.35249778e-01],
       [-1.89055118e-01,  3.50539916e-01, -1.14129731e-01,
        -1.04301739e-01,  4.05975480e-01],
       [ 2.50839914e-01,  9.41656327e-02, -2.44858695e-01,
         2.66457727e-01, -4.81195363e-01],
       [ 4.63655478e-01, -1.28413430e-02,  3.75783717e-01,
         3.94226703e-01, -5.35489771e-01],
       [-5.76371869e-02,  1.22544950e-01, -3.36368719e-01,
        -9.90442193e-02,  2.04501332e-01]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
np.ones((5,3)) @ np.ones((3,2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
a = np.arange(0,11)
a[(a > 3) & (a < 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


numpy.sumとsumの挙動の違い

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z = np.array([1,2,3])

print(Z**Z)
print(2 << Z >>2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z) エラーが出る

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0))

print(np.array(0) // np.array(0))

print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


<ipython-input-29-72dab2b1b7c8>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-29-72dab2b1b7c8>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
np.random.random(1).round()

array([0.])

#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
a = np.random.randint(1,5,5)
b = np.random.randint(1,5,5)

print("a:",a)
print("b:",b)
print(intersect1d(a,b))

a: [4 4 3 4 4]
b: [2 4 4 1 4]
[4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
defaults = np.seterr(all="ignore")
defaults

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [33]:
np.seterr(**defaults)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


<ipython-input-34-54f6324019e1>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [35]:
today = np.datetime64("today")
tomorrow = today - np.timedelta64(-1)
yesterday = today - np.timedelta64(1)
yesterday

numpy.datetime64('2021-03-22')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [36]:
np.arange("2016-07", "2016-08", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [37]:
a = np.ones(3) * 1
b = np.ones(3) * 2

np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a, out=a)
np.multiply(b, a)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [38]:
a = np.random.uniform(1,5,5)
print(a)
print(a - a%1)
print(a//1)
print(a.astype(int))
print(np.floor_divide(a,1))

[1.23936063 3.55565849 1.18117741 1.12509255 4.27986959]
[1. 3. 1. 1. 4.]
[1. 3. 1. 1. 4.]
[1 3 1 1 4]
[1. 3. 1. 1. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [39]:
a = np.arange(5)
np.tile(a,(4,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [40]:
def abc():
    for i in range(10):
        yield i
        
np.fromiter(abc(), dtype=float, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [41]:
np.linspace(0,1,11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [42]:
a = np.random.randint(1,10,10)
np.sort(a)

array([2, 3, 4, 5, 7, 8, 8, 8, 9, 9])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [43]:
a = np.ones(100)
%timeit np.add.reduce(a)

%timeit np.sum(a)

%timeit sum(a)

570 ns ± 11.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.61 µs ± 10.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.61 µs ± 9.87 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [44]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)

#完全一致
print(np.all(a==b))

#多少の猶予あり一致
print(np.allclose(a,b))

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [45]:
a = np.arange(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
import matplotlib.pyplot as plt


z = np.random.random((10, 2))
x,y = z[:,0],z[:,1]

radii = np.sqrt(x**2 + y**2)
theta = np.arctan2(y,x)
    
# 極座標系グラフ
ax2 = plt.subplot(1,1,1,polar=True)
ax2.scatter(theta,radii)
ax2.set_rmax(1)
ax2.grid(True)

plt.show()

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
a = np.random.random(10)
a[np.argmax(a)] = 0
a

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
print(Z)

Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
x = np.arange(3)
y = x + 0.5

# cの行列を作成
c = 1.0/np.subtract.outer(x,y)

# cの行列式
np.linalg.det(c)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
import numpy

a = numpy.arange(10000)

# 全て表示する
# numpy.set_printoptions(threshold=float("inf"))

# デフォルト値に戻す
# numpy.set_printoptions(threshold=1000)

print(a)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [54]:
a = np.arange(0, 100, 2)

b = np.random.uniform(0,100)

np.searchsorted(a, b)

5

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [57]:
z = np.zeros(10,[("position", [("x", float),
                               ("y", float)]),
                 ("color",    [("r", float),
                               ("g", float),
                               ("b", float)])])
z

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [60]:
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.3356397  0.24395396 0.27446009 0.46272965 0.44228129
  0.04745271 0.34649277 0.32440671 0.3619265 ]
 [0.3356397  0.         0.57912922 0.57864567 0.74051582 0.51204182
  0.36624841 0.6243866  0.46967203 0.05048162]
 [0.24395396 0.57912922 0.         0.14801178 0.35484927 0.52080735
  0.21526178 0.27535843 0.38727018 0.60282655]
 [0.27446009 0.57864567 0.14801178 0.         0.50251004 0.39513998
  0.22914052 0.42147684 0.26697839 0.59046647]
 [0.46272965 0.74051582 0.35484927 0.50251004 0.         0.85930935
  0.47115654 0.11812139 0.72600245 0.78179104]
 [0.44228129 0.51204182 0.52080735 0.39513998 0.85930935 0.
  0.41078255 0.75566629 0.13396019 0.4881208 ]
 [0.04745271 0.36624841 0.21526178 0.22914052 0.47115654 0.41078255
  0.         0.35807973 0.28761066 0.38786982]
 [0.34649277 0.6243866  0.27535843 0.42147684 0.11812139 0.75566629
  0.35807973 0.         0.62381139 0.66485192]
 [0.32440671 0.46967203 0.38727018 0.26697839 0.72600245 0.13396019
  0.28761066 0.62381

In [61]:
from scipy.spatial import distance

Z = np.random.random((10,2))
distance.cdist(Z,Z)

array([[0.        , 0.10400242, 0.67359254, 0.39509121, 0.78401573,
        0.56080447, 0.19189031, 0.54907101, 0.60343416, 0.25442547],
       [0.10400242, 0.        , 0.74940313, 0.3932328 , 0.88495892,
        0.64223845, 0.28639963, 0.59294472, 0.70292145, 0.15577079],
       [0.67359254, 0.74940313, 0.        , 1.02199405, 0.74556489,
        0.85985848, 0.49153465, 1.03914834, 0.68383844, 0.82918325],
       [0.39509121, 0.3932328 , 1.02199405, 0.        , 0.83881721,
        0.4783699 , 0.53718197, 0.27761173, 0.6630304 , 0.4906934 ],
       [0.78401573, 0.88495892, 0.74556489, 0.83881721, 0.        ,
        0.38020072, 0.66330862, 0.65044603, 0.18543215, 1.03843302],
       [0.56080447, 0.64223845, 0.85985848, 0.4783699 , 0.38020072,
        0.        , 0.53425545, 0.27082019, 0.2390612 , 0.79539869],
       [0.19189031, 0.28639963, 0.49153465, 0.53718197, 0.66330862,
        0.53425545, 0.        , 0.61344486, 0.49853872, 0.41332187],
       [0.54907101, 0.59294472, 1.0391483

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [65]:
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)

Y = Z.view(np.int32)
print(Y)

Y[:] = Z
print(Y)

#理解が出来ない。 astpyeでいいのでは？

[29.457994 29.088829 29.891634 87.123856 59.2731    4.534062 61.10171
  2.599239 66.765915 10.878668]
[1105963513 1105769964 1106190865 1118715754 1114445736 1083250441
 1114925095 1076255215 1116047398 1093537542]
[29 29 29 87 59  4 61  2 66 10]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [72]:
from io import StringIO

s = StringIO('''
             1, 2, 3, 4, 5
             6,  ,  , 7, 8
              ,  , 9,10,11
              ''')

np.genfromtxt(s, delimiter=",", dtype=int8)

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]], dtype=int8)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [79]:
Z = np.arange(9).reshape(3,3)
print(Z)

for index, value in np.ndenumerate(Z):
    print(index, value)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### ２次元ガウス配列(要学習）


$$確率密度関数	𝑓(𝑋)=\frac{1}{\sqrt2πσ^2}exp[−\frac{(𝑥−μ)^2}{2σ^2}]$$
$$期待値（平均）	𝐸(𝑋)=μ$$
$$分散	𝑉(𝑋)=σ^2$$
$$標準偏差	𝑆𝐷(𝑋)=σ$$

In [81]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)

sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [94]:
n = 5
p = 2
z = np.zeros((n,n))

x = np.random.choice(range(n*n),p,replace=False)
print(x)

np.put(z, x, 1)
z

[7 2]


array([[0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)  
行列の各行の平均を減算します

In [99]:
a = np.random.randint(0,10,(2,4))
print(a)

print(a - a.mean(axis=1,keepdims=True))

[[6 5 7 9]
 [1 3 4 3]]
[[-0.75 -1.75  0.25  2.25]
 [-1.75  0.25  1.25  0.25]]


#### 59. How to sort an array by the nth column? (★★☆)  
n番目の列で配列を並べ替える方法は？

In [116]:
a = np.random.randint(1,10,(3,3))
print(a)

print(a[a[:,1].argsort()])

[[2 6 3]
 [3 3 3]
 [6 3 4]]
[[3 3 3]
 [6 3 4]
 [2 6 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)  
特定の2D配列にnull列があるかどうかを確認するにはどうすればよいですか？

In [150]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[0 1 1 2 1 1 1 2 0 2]
 [2 0 1 1 0 2 1 1 0 0]
 [0 0 1 0 2 2 1 0 2 1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)  
配列内の指定された値から最も近い値を見つけます

In [153]:
Z = np.random.uniform(0,1,(10,10))
print(Z)

#指定した値
z = 0.5

# np.absは絶対値をとる
# np.flatはイテレータを返す
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

[[0.48046758 0.34773957 0.20757628 0.1862667  0.7371921  0.47475538
  0.77797905 0.51554222 0.04139205 0.75916558]
 [0.90638562 0.27376069 0.72915712 0.51846823 0.83706727 0.60390523
  0.29855207 0.04377496 0.15124145 0.26338908]
 [0.56876923 0.65767149 0.03102574 0.15629763 0.14859717 0.53314981
  0.34260156 0.47785749 0.0668472  0.1361275 ]
 [0.19823434 0.45972761 0.35631952 0.09772123 0.51746392 0.93942118
  0.16708114 0.70356894 0.89711673 0.00311985]
 [0.78284598 0.83198248 0.6538681  0.04456976 0.91761427 0.98310309
  0.90666656 0.5358522  0.54920014 0.13341907]
 [0.7289202  0.01561289 0.41006103 0.6734081  0.26494628 0.86682975
  0.81149893 0.71189922 0.74351343 0.04959599]
 [0.54580739 0.05410638 0.7311069  0.33346724 0.11925418 0.5880301
  0.29364719 0.81309833 0.01895245 0.74461264]
 [0.32465398 0.23041838 0.40116812 0.57235368 0.52033318 0.27118241
  0.07012179 0.10384164 0.63389534 0.09327713]
 [0.34085182 0.15732737 0.72439855 0.70740695 0.64746844 0.94873744
  0.56061941 

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)  
形状が（1,3）と（3,1）の2つの配列を考えると、イテレーターを使用してそれらの合計を計算する方法は？

In [185]:
A = np.arange(3).reshape(3,1)
print(A)
B = np.arange(3).reshape(1,3)
print(B)

it = np.nditer([A,B,None])
print(it)

for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)  
name属性を持つ配列クラスを作成します

In [197]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)  
与えられたベクトルを考えてみましょう。2番目のベクトルでインデックス付けされた各要素に1を追加する方法（インデックスの繰り返しに注意してください）？

In [202]:
z = np.ones(10)
print(z)
i = np.random.randint(0,len(z), 20)
print(i)
z += np.bincount(i, minlength=len(z))
print(z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5 9 0 1 7 5 9 1 9 1 3 7 3 1 1 1 1 1 3 3]
[2. 9. 1. 5. 1. 3. 1. 3. 1. 4.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)  
インデックスリスト（I）に基づいて、ベクトル（X）の要素を配列（F）に累積する方法は？

In [213]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)
（dtype = ubyte）の（w、h、3）画像を考慮して、一意の色の数を計算します

#理解不能

In [223]:
w,h = 16,16
i = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
f = i[...,0]*256*256 + i[...,1]*256 + i[...,2]
n = len(np.unique(f))
print(np.unique(i))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
4次元配列を考えると、最後の2つの軸の合計を一度に取得するにはどうすればよいですか？

In [227]:
random.seed(0)
A = np.random.randint(0,5,(2,2,2,2))
print(A)
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-1,-2))
print("合計\n",sum)

[[[[4 0]
   [3 3]]

  [[3 1]
   [3 2]]]


 [[[4 0]
   [0 4]]

  [[2 1]
   [0 1]]]]
合計
 [[10  9]
 [ 8  4]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)  
1次元のベクトルDを考えると、サブセットインデックスを記述する同じサイズのベクトルSを使用して、Dのサブセットの平均を計算する方法は？

In [234]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.51255389 0.62970415 0.50348424 0.45383278 0.48338889 0.57251331
 0.47262951 0.4622803  0.44818632 0.49947316]


#### 69. How to get the diagonal of a dot product? (★★★)  
内積の対角線を取得するにはどうすればよいですか？

In [238]:
answer(69)

# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)


In [254]:
a = np.random.randint(0,3,(2,2))
b = np.random.randint(0,3,(2,2))
print(a)
print(b)
c = a@b
print(c)
print(np.diag(c))

[[0 0]
 [1 1]]
[[1 1]
 [0 1]]
[[0 0]
 [1 2]]
[0 2]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
ベクトル[1、2、3、4、5]について考えてみましょう。各値の間に、3つの連続するゼロがインターリーブされた新しいベクトルを作成する方法を教えてください。

In [261]:
a = [1, 2, 3, 4, 5]
nz = 3
z0 = np.zeros(len(a) + (len(a)-1)*(nz))
print(z0)
z0[::nz+1] = a
print(z0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)