# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)
numpyバージョンと構成を印刷します

In [3]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)
配列のメモリサイズを見つける方法

In [5]:
Z = np.zeros((10,10))
print(f"{Z.size * Z.itemsize} bytes")

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
コマンドラインからnumpyadd関数のドキュメントを取得するにはどうすればよいですか？

In [24]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
サイズ10のヌルベクトルを作成しますが、5番目の値は1です

In [25]:
a = np.zeros(10)
a[5] = 1
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
10から49の範囲の値を持つベクトルを作成します


In [ ]:
np.arange(10,50)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [26]:
a = np.arange(10,50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [27]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [28]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [34]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)
ランダムな値で3x3x3配列を作成します

In [35]:
np.random.random((3,3,3))

array([[[0.59112457, 0.47412711, 0.93456528],
        [0.80993979, 0.63438016, 0.66849238],
        [0.66920941, 0.04104804, 0.38395956]],

       [[0.68626883, 0.25910566, 0.41860142],
        [0.56378663, 0.28235535, 0.43067014],
        [0.04999518, 0.91692041, 0.44105736]],

       [[0.59499517, 0.3090396 , 0.4966001 ],
        [0.17041248, 0.87891627, 0.18192558],
        [0.94553283, 0.39078545, 0.19548618]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
ランダムな値で10x10の配列を作成し、最小値と最大値を見つけます


In [36]:
a = np.random.random((10,10))
print(a.max(),a.min())

0.990243379301106 0.030864387894626755


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
サイズ30のランダムなベクトルを作成し、平均値を見つけます

In [37]:
np.random.random(30).mean()

0.4590255379177571

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
境界に1、内側に0の2次元配列を作成します


In [38]:
a = np.ones((5,5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [15]:
a = np.ones((5,5))
np.pad(a,(1,1))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
次の式の結果は何ですか？

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [16]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
対角のすぐ下に値1、2、3、4の5x5行列を作成します

In [43]:
np.diag(np.arange(1,5),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
8x8マトリックスを作成し、チェッカーボードパターンで塗りつぶします


In [45]:
a = np.zeros((8,8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
（6,7,8）形状配列を考えてみましょう。100番目の要素のインデックス（x、y、z）は何ですか？


In [56]:
X

NameError: name 'X' is not defined

In [57]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
タイル関数を使用してチェッカーボード8x8マトリックスを作成します

In [58]:
a = np.array([[0,1],[1,0]])
np.tile(a,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)
5x5のランダム行列を正規化する

In [59]:
a = np.random.random((5,5))

(a - a.mean()) / ((a.max()) - (a.min()))

array([[ 0.45949396,  0.46429953, -0.52874718, -0.39979   ,  0.28709283],
       [-0.12023098,  0.47077055,  0.07438773,  0.19997117, -0.11694796],
       [-0.32386658, -0.32174465,  0.47125282, -0.15741513,  0.26737427],
       [-0.04475585, -0.16885051,  0.35151299, -0.43433759, -0.46113353],
       [ 0.44888802, -0.51771608,  0.25596308,  0.06436055, -0.21983147]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
色を4つの符号なしバイト（RGBA）として記述するカスタムdtypeを作成します


In [63]:
x

NameError: name 'x' is not defined

In [64]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
5x3行列に3x2行列を掛けます（実際の行列の積）

In [65]:
np.ones((5,3)) @ np.ones((3,2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
1D配列が与えられた場合、3から8までのすべての要素を適切に無効にします。

In [66]:
a = np.arange(0,11)
a[(a > 3) & (a < 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
次のスクリプトの出力は何ですか？

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [67]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


numpy.sumとsumの挙動の違い

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
整数ベクトルZを考えてみましょう。これらの式のどれが有効ですか？

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [68]:
Z = np.array([1,2,3])

print(Z**Z)
print(2 << Z >>2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z) エラーが出る

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions?
次の式の結果は何ですか？

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [69]:
print(np.array(0) / np.array(0))

print(np.array(0) // np.array(0))

print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


<ipython-input-69-72dab2b1b7c8>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-69-72dab2b1b7c8>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)
フロート配列をゼロから丸める方法は？


In [70]:
np.random.random(1).round()

array([1.])

#### 30. How to find common values between two arrays? (★☆☆)
2つの配列間で共通の値を見つける方法は？

In [72]:
a = np.random.randint(1,5,5)
b = np.random.randint(1,5,5)

print("a:",a)
print("b:",b)
print(intersect1d(a,b))

a: [3 3 4 2 4]
b: [2 3 3 2 1]
[2 3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
すべてのnumpy警告を無視する方法（非推奨）？

In [73]:
defaults = np.seterr(all="ignore")
defaults

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [74]:
np.seterr(**defaults)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
次の表現は本当ですか？
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [75]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


<ipython-input-75-54f6324019e1>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
昨日、今日、明日の日付を取得するにはどうすればよいですか？

In [76]:
today = np.datetime64("today")
tomorrow = today - np.timedelta64(-1)
yesterday = today - np.timedelta64(1)
yesterday

numpy.datetime64('2021-03-29')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
2016年7月に対応するすべての日付を取得するにはどうすればよいですか？

In [82]:
np.arange("2016-07", "2016-08", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
（（A + B）*（-A / 2））をその場で（コピーなしで）計算する方法は？

In [83]:
a = np.ones(3) * 1
b = np.ones(3) * 2

np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a, out=a)
np.multiply(b, a)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
4つの異なる方法を使用して、正の数のランダム配列の整数部分を抽出します

In [94]:
a = np.random.uniform(1,5,5)
print(a)
print(a - a%1)
print(a//1)
print(a.astype(int))
print(np.floor_divide(a,1))

[1.98091826 3.12417104 4.94943386 2.23531613 1.49279198]
[1. 3. 4. 2. 1.]
[1. 3. 4. 2. 1.]
[1 3 4 2 1]
[1. 3. 4. 2. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
0から4の範囲の行値を持つ5x5行列を作成します

In [95]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
10個の整数を生成し、それを使用して配列を作成するジェネレーター関数について考えてみます。

In [99]:
def abc():
    for i in range(10):
        yield i
        
np.fromiter(abc(),dtype=float, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [204]:
def abc():
    for i in range(10):
        yield i
        
np.fromiter(abc(), dtype=float, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
0から1の範囲の値を持つサイズ10のベクトルを作成し、両方を除外します

In [103]:
np.linspace(0,1,11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)
サイズ10のランダムなベクトルを作成し、並べ替えます


In [104]:
a = np.random.randint(1,10,10)
np.sort(a)

array([1, 1, 2, 2, 2, 3, 3, 5, 7, 8])

#### 41. How to sum a small array faster than np.sum? (★★☆)
np.sumよりも速く小さな配列を合計する方法は？

In [110]:
a = np.ones(10)
%timeit np.add.reduce(a)

%timeit np.sum(a)

%timeit sum(a)

505 ns ± 1.74 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.57 µs ± 10.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.55 µs ± 10.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)
2つのランダム配列AとBを検討し、それらが等しいかどうかを確認します

In [108]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)

#完全一致
print(np.all(a==b))

#多少の猶予あり一致
print(np.allclose(a,b))

False
False


#### 43. Make an array immutable (read-only) (★★☆)
配列を不変にする（読み取り専用）

In [109]:
a = np.arange(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
デカルト座標を表すランダムな10x2行列を考え、それらを極座標に変換します

In [ ]:
import matplotlib.pyplot as plt


z = np.random.random((10, 2))
x,y = z[:,0],z[:,1]

radii = np.sqrt(x**2 + y**2)
theta = np.arctan2(y,x)
    
# 極座標系グラフ
ax2 = plt.subplot(1,1,1,polar=True)
ax2.scatter(theta,radii)
ax2.set_rmax(1)
ax2.grid(True)

plt.show()

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
サイズ10のランダムベクトルを作成し、最大値を0に置き換えます

In [ ]:
a = np.random.random(10)
a[np.argmax(a)] = 0
a

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
[0,1] x [0,1]領域をカバーするx座標とy座標を持つ構造化配列を作成します

In [117]:
Z = np.zeros((5,5), [('x',float),('y',float)])
print(Z)

Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]
 [(0., 0.) (0., 0.) (0., 0.) (0., 0.) (0., 0.)]]
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
XとYの2つの配列が与えられた場合、コーシー行列Cを作成します（Cij = 1 /（xi -yj））


In [125]:
X

NameError: name 'X' is not defined

In [257]:
x = np.arange(3)
y = x + 0.5

# cの行列を作成
c = 1.0/np.subtract.outer(x,y)

# cの行列式
np.linalg.det(c)

-15.17037037037037

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
各スカラー型numpyの表現可能な最小値と最大値を出力します

In [130]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)
配列のすべての値を出力するにはどうすればよいですか？

In [131]:
import numpy

a = numpy.arange(10000)

# 全て表示する
# numpy.set_printoptions(threshold=float("inf"))

# デフォルト値に戻す
# numpy.set_printoptions(threshold=1000)

print(a)

[   0    1    2 ... 9997 9998 9999]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
ベクトル内で（特定のスカラーに）最も近い値を見つける方法は？


In [132]:
a = np.random.random(10)
print(a)

b = 0.5
print(b)

%timeit a[abs(a - b).argmin()]

[0.76882867 0.58076077 0.98139908 0.46024468 0.55363197 0.61627921
 0.23343945 0.64627918 0.95163358 0.04872836]
0.5
720 ns ± 1.58 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
位置（x、y）と色（r、g、b）を表す構造化配列を作成します

In [134]:
z = np.zeros(10,[("position", [("x", float),
                               ("y", float)]),
                 ("color",    [("r", float),
                               ("g", float),
                               ("b", float)])])
z

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
座標を表す形状（100,2）のランダムベクトルを考え、ポイントごとの距離を見つけます


In [136]:
from scipy.spatial import distance

z = np.random.random((10,2))
distance.cdist(z,z)

array([[0.        , 0.20789254, 0.41680347, 0.64261413, 0.56324511,
        0.32319222, 0.66912473, 0.64995148, 0.30238431, 0.27860135],
       [0.20789254, 0.        , 0.28739349, 0.46609395, 0.75535957,
        0.26624446, 0.60435838, 0.48920657, 0.44126305, 0.07077516],
       [0.41680347, 0.28739349, 0.        , 0.25269904, 0.82856701,
        0.54634389, 0.33430337, 0.23953867, 0.70596821, 0.26352637],
       [0.64261413, 0.46609395, 0.25269904, 0.        , 1.08066108,
        0.67656417, 0.41210201, 0.07397893, 0.9073159 , 0.41032131],
       [0.56324511, 0.75535957, 0.82856701, 1.08066108, 0.        ,
        0.86041642, 0.879474  , 1.05504195, 0.62840127, 0.8213651 ],
       [0.32319222, 0.26624446, 0.54634389, 0.67656417, 0.86041642,
        0.        , 0.87015556, 0.71708721, 0.32912199, 0.28470797],
       [0.66912473, 0.60435838, 0.33430337, 0.41210201, 0.879474  ,
        0.87015556, 0.        , 0.34212738, 0.9714201 , 0.59386431],
       [0.64995148, 0.48920657, 0.2395386

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
float（32ビット）配列を整数（32ビット）に変換するにはどうすればよいですか？

In [147]:
X

NameError: name 'X' is not defined

In [148]:
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)

Y = Z.view(np.int32)
print(Y)

Y[:] = Z
print(Y)

#理解が出来ない。 astpyeでいいのでは？

[3.8007263e+01 3.9384094e+01 8.2967194e+01 3.1255536e-02 1.7443382e+01
 7.8124245e+01 8.1748505e+01 2.3924835e+01 4.3220512e+01 3.0355387e+01]
[1108871024 1109231952 1118170932 1023411662 1099664396 1117536157
 1118011196 1103062544 1110237646 1106434005]
[38 39 82  0 17 78 81 23 43 30]


#### 54. How to read the following file? (★★☆)
次のファイルの読み方は？
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [152]:
X

NameError: name 'X' is not defined

In [153]:
from io import StringIO

s = StringIO('''
             1, 2, 3, 4, 5
             6,  ,  , 7, 8
              ,  , 9,10,11
              ''')

np.genfromtxt(s, delimiter=",", dtype=int8)

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]], dtype=int8)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
numpy配列の列挙に相当するものは何ですか？

In [159]:
Z = np.arange(9).reshape(3,3)
print(Z)

for index, value in np.ndenumerate(Z):
    print(index, value)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### ２次元ガウス配列(要学習）


$$確率密度関数	𝑓(𝑋)=\frac{1}{\sqrt2πσ^2}exp[−\frac{(𝑥−μ)^2}{2σ^2}]$$
$$期待値（平均）	𝐸(𝑋)=μ$$
$$分散	𝑉(𝑋)=σ^2$$
$$標準偏差	𝑆𝐷(𝑋)=σ$$

In [162]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)

sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)
p要素を2D配列にランダムに配置するにはどうすればよいですか？

In [182]:
XY

NameError: name 'XY' is not defined

In [184]:
n = 5
p = 2
z = np.zeros((n,n))

x = np.random.choice(range(n*n),p,replace=False)
print(x)

np.put(z, x, 1)
z

[ 0 16]


array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)  
行列の各行の平均を減算します

In [198]:
XY

NameError: name 'XY' is not defined

In [199]:
a = np.random.randint(0,10,(2,4))
print(a)

print(a - a.mean(axis=1,keepdims=True))

[[8 7 1 7]
 [4 0 6 3]]
[[ 2.25  1.25 -4.75  1.25]
 [ 0.75 -3.25  2.75 -0.25]]


#### 59. How to sort an array by the nth column? (★★☆)  
n番目の列で配列を並べ替える方法は？

In [243]:
XY

NameError: name 'XY' is not defined

In [244]:
a = np.random.randint(1,10,(3,3))
print(a)

print(a[a[:,1].argsort()])

[[5 3 7]
 [3 4 4]
 [7 4 3]]
[[5 3 7]
 [3 4 4]
 [7 4 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)  
特定の2D配列にnull列があるかどうかを確認するにはどうすればよいですか？

In [252]:
XY

NameError: name 'XY' is not defined

In [253]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[2 1 2 2 0 1 2 2 0 1]
 [2 1 1 2 2 1 0 2 1 1]
 [1 0 0 2 1 1 1 2 2 2]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)  
配列内の指定された値から最も近い値を見つけます

In [267]:
a = np.random.rand(3,3)
print(a)
z = np.random.rand(1)
print(z)

# np.absは絶対値をとる、一番差が小さいインデックスを抽出
index = np.abs(z - a).argmin()

# np.flatはイテレータを返す
a.flat[index]

[[0.77031113 0.17653801 0.75485218]
 [0.66571524 0.49459488 0.93182783]
 [0.86867135 0.78544823 0.62184349]]
[0.53126556]


0.494594878622845

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)  
形状が（1,3）と（3,1）の2つの配列を考えると、イテレーターを使用してそれらの合計を計算する方法は？

In [269]:
# for以降、理解が出来ない

In [329]:
A = np.arange(3).reshape(3,1)
print(A)
B = np.arange(3).reshape(1,3)
print(B)

it = np.nditer([A,B,None])
print(it)

for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)  
name属性を持つ配列クラスを作成します

In [332]:
XY

NameError: name 'XY' is not defined

In [333]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10),"range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)  
与えられたベクトルを考えてみましょう。2番目のベクトルでインデックス付けされた各要素に1を追加する方法（インデックスの繰り返しに注意してください）？

In [344]:
z = np.ones(10)
print(z)
i = np.random.randint(0,len(z), 20)
print(i)
z += np.bincount(i, minlength=len(z))
print(z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3 0 0 1 8 4 5 1 5 6 2 6 0 5 7 8 9 8 5 8]
[4. 3. 2. 2. 2. 5. 3. 2. 5. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)  
インデックスリスト（I）に基づいて、ベクトル（X）の要素を配列（F）に累積する方法は？

In [355]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)
（dtype = ubyte）の（w、h、3）画像を考慮して、一意の色の数を計算します

#理解不能

In [356]:
w,h = 16,16
i = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
f = i[...,0]*256*256 + i[...,1]*256 + i[...,2]
n = len(np.unique(f))
print(np.unique(i))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
4次元配列を考えると、最後の2つの軸の合計を一度に取得するにはどうすればよいですか？

In [360]:
random.seed(0)
A = np.random.randint(0,5,(2,2,2,2))
print(A)
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-1,-2))
print("合計\n",sum)

[[[[4 0]
   [3 3]]

  [[3 1]
   [3 2]]]


 [[[4 0]
   [0 4]]

  [[2 1]
   [0 1]]]]
合計
 [[10  9]
 [ 8  4]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)  
1次元のベクトルDを考えると、サブセットインデックスを記述する同じサイズのベクトルSを使用して、Dのサブセットの平均を計算する方法は？

In [366]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.49484928 0.46308052 0.64102249 0.47363971 0.58260725 0.50308793
 0.58159979 0.51907569 0.6281725  0.45727394]


#### 69. How to get the diagonal of a dot product? (★★★)  
内積の対角線を取得するにはどうすればよいですか？

In [372]:
a = np.random.randint(0,3,(2,2))
b = np.random.randint(0,3,(2,2))
print(a)
print(b)
c = a@b
print(c)
print(np.diag(c))

[[2 0]
 [1 1]]
[[0 2]
 [0 1]]
[[0 4]
 [0 3]]
[0 3]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
ベクトル[1、2、3、4、5]について考えてみましょう。各値の間に、3つの連続するゼロがインターリーブされた新しいベクトルを作成する方法を教えてください。

In [389]:
a = [1, 2, 3, 4, 5]
nz = 3
z0 = np.zeros(len(a) + (len(a)-1)*(nz))
print(z0)
z0[::nz+1] = a
print(z0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
次元（5,5,3）の配列を考えてみましょう。次元（5,5）の配列でそれを多重化する方法は？

In [399]:
XY

NameError: name 'XY' is not defined

In [52]:
A = np.ones((5,5,3))
print(A)
B = 2*np.ones((5,5))
print(B)
print(B[:,:,None])
print(A * B[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]]
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)
配列の2つの行を交換する方法は？

In [53]:
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
（頂点が共有されている）10個の三角形を表す10個のトリプレットのセットを検討し、すべての三角形を構成する一意の線分のセットを見つけます。


In [54]:
# 理解不能
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 58) ( 0, 86) (17, 22) (17, 30) (18, 70) (18, 71) (21, 46) (21, 73)
 (22, 30) (28, 73) (28, 81) (39, 39) (39, 75) (41, 49) (41, 93) (43, 83)
 (43, 92) (46, 73) (49, 93) (58, 86) (66, 85) (66, 91) (70, 71) (73, 81)
 (83, 92) (85, 91) (89, 91) (89, 96) (91, 96)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
bincountに対応するソートされた配列Cが与えられた場合、np.bincount（A）== Cとなるような配列Aを生成するにはどうすればよいですか？

In [55]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)


print(np.arange(len(C)))
# numpy.repeat(a, n) はスカラーや配列 a の各要素を n 回 繰り返す 配列を生成します。
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[0 1 2 3 4 5 6]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)
配列上のスライディングウィンドウを使用して平均を計算するにはどうすればよいですか？


In [63]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    # np.cumsum()で累積和を取得
    ret = np.cumsum(a, dtype=float)
    print(ret)
    print(ret[n:])
    print(ret[:-n])
    # スライド幅 -1 の幅を算出（−１は重複している値)
    ret[n:] = ret[n:] - ret[:-n]
    print(ret[n:])
    print(ret[n - 1:])
    # 重複して削除された値を補填して平均化
    return ret[n - 1:] / n
Z = np.arange(5)
print(Z)
print(moving_average(Z, n=3))

[0 1 2 3 4]
[ 0.  1.  3.  6. 10.]
[ 6. 10.]
[0. 1.]
[6. 9.]
[3. 6. 9.]
[1. 2. 3.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
1次元配列Zを考え、最初の行が（Z [0]、Z [1]、Z [2]）で、後続の各行が1ずつシフトされる2次元配列を作成します（最後の行は（Z [ -3]、Z [-2]、Z [-1]）


In [67]:
from numpy.lib.stride_tricks import as_strided

def roll(a, window):
    # shapeサイズを求める>>>(8,3)
    shape = (a.size - window + 1, window)
    # stride_tricks.as_stridedの引数strides（スキップ幅)は、byte単位で計算するので、aのbyte数を抽出する。
    strides = (a.itemsize, a.itemsize)
    return as_strided(a, shape=shape, strides=strides)

roll(np.arange(10),3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
ブール値を無効にする方法、またはフロートの符号をインプレースで変更する方法は？

In [73]:
# Author: Nathaniel J. Smith

#ブール値の無効（否定）
Z = np.random.randint(0,2,100)
z = np.logical_not(Z, out=Z)
print(Z)
print(z)

#インプレース
A = np.random.uniform(-1.0,1.0,100)
a = np.negative(Z, out=Z)
print(A)
print(a)

[0 0 0 1 1 0 1 1 0 1 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 0
 0 1 0 1 1 1 1 1 0 0 1 1 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0
 1 1 0 1 1 0 1 0 1 0 1 1 0 1 1 1 1 1 0 1 0 1 1 0 0 0]
[0 0 0 1 1 0 1 1 0 1 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 0
 0 1 0 1 1 1 1 1 0 0 1 1 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0
 1 1 0 1 1 0 1 0 1 0 1 1 0 1 1 1 1 1 0 1 0 1 1 0 0 0]
[-0.20100218 -0.39633825  0.55043955  0.85242586 -0.34937939  0.90574134
 -0.97210321  0.06693136 -0.39083594  0.76572    -0.49875456  0.35482366
  0.62084818 -0.1357039   0.50426904  0.6592045  -0.24193246 -0.80690078
 -0.48772085  0.18387032 -0.0470456  -0.02413086 -0.0829709   0.04918524
 -0.11596936  0.70526985 -0.13312205  0.65374074  0.01868413 -0.82724604
  0.32007972 -0.58681079  0.69455065  0.36271826 -0.6432653  -0.86028197
 -0.98062366  0.78409932 -0.73306958  0.55838395  0.85032685  0.4303575
 -0.01836277 -0.06100339  0.76541858 -0.02317988 -0.17086503 -0.6517761
 -0.049421

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
線（2d）と点pを表す2組の点P0、P1を考えてみましょう。pから各線i（P0 [i]、P1 [i]）までの距離を計算する方法は？


点と直線の公式  
http://www.info.hiroshima-cu.ac.jp/~miyazaki/knowledge/tech0044.html

In [74]:
p = np.random.randint(-10,10,(1,2))
print(p)

P0 = np.random.randint(-10,10,(1,2))
P1 = np.random.randint(-10,10,(1,2))
print(P0, P1)

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    print(U)
    U = U.reshape(len(U),1)
    print(U)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

print(distance(P0, P1, p))

[[ 5 -7]]
[[ 4 -5]] [[1 9]]
[-0.15121951]
[[-0.15121951]]
[0.55874424]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)
線（2d）を表す2組の点P0、P1と1組の点Pを考えてみましょう。各点j（P [j]）から各線i（P0 [i]、P1 [i]）までの距離を計算する方法は？


In [75]:
p = np.random.randint(-10,10,(10,2))
print(p)

print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[-4 -4]
 [ 9 -4]
 [-8 -4]
 [-5 -5]
 [ 3 -1]
 [-6  3]
 [ 7 -7]
 [ 3  9]
 [-2  3]
 [-5  6]]
[0.18536585]
[[0.18536585]]
[-0.00487805]
[[-0.00487805]]
[0.24390244]
[[0.24390244]]
[0.13170732]
[[0.13170732]]
[0.28780488]
[[0.28780488]]
[0.69268293]
[[0.69268293]]
[-0.1804878]
[[-0.1804878]]
[0.97073171]
[[0.97073171]]
[0.63414634]
[[0.63414634]]
[0.88292683]
[[0.88292683]]
[[ 7.61289022]
 [ 5.09854116]
 [11.52409988]
 [ 8.80022173]
 [ 0.13968606]
 [ 8.10179143]
 [ 2.51434906]
 [ 1.95560483]
 [ 4.19058177]
 [ 6.49540175]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
任意の配列を検討し、固定された形状で特定の要素を中心とするサブパーツを抽出する関数を記述します（必要に応じて塗りつぶし値のあるパッド）

In [77]:
Z = np.random.randint(0,3,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R  = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 1 0 2 0 1 2 0 0 1]
 [1 0 2 1 2 1 2 0 2 0]
 [2 0 0 2 1 0 2 0 0 2]
 [0 1 2 0 2 2 1 2 2 2]
 [2 2 0 2 0 0 1 1 2 1]
 [0 2 1 0 1 2 1 2 2 1]
 [2 2 2 2 1 2 2 2 2 0]
 [1 1 0 1 0 1 1 2 0 0]
 [1 0 2 1 1 2 0 0 1 1]
 [2 0 0 0 2 2 1 1 1 1]]
[[0 0 0 0 0]
 [0 0 1 0 2]
 [0 1 0 2 1]
 [0 2 0 0 2]
 [0 0 1 2 0]]


<ipython-input-77-5859bd2b32fe>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
配列Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]を考えてみましょう。配列を生成する方法は、R = [[1,2,3、 4]、[2,3,4,5]、[3,4,5,6]、...、[11,12,13,14]]？

In [78]:
Z = np.arange(1,15,dtype=np.uint32)
R = as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)
行列の階数を計算する

In [84]:
a = np.random.randint(0,5,(16,4))
print(a)

np.linalg.matrix_rank(a)

[[2 3 2 2]
 [1 3 3 0]
 [4 3 3 0]
 [0 1 4 4]
 [1 0 0 0]
 [3 4 4 2]
 [2 3 3 4]
 [2 1 0 4]
 [1 3 0 3]
 [2 1 0 0]
 [3 4 1 0]
 [0 2 1 1]
 [0 1 1 0]
 [0 3 3 3]
 [3 1 2 0]
 [0 4 2 2]]


4

#### 83. How to find the most frequent value in an array?
配列内で最も頻度の高い値を見つける方法


In [92]:
a = np.random.randint(0,10,30)
print(a)

a[np.bincount(a).argmax()]

[5 0 5 8 9 8 2 5 3 1 7 3 8 5 5 1 9 7 2 1 0 1 0 1 1 6 8 8 3 2]


0

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
ランダムな10x10行列からすべての隣接する3x3ブロックを抽出します


In [98]:
Z = np.random.randint(0,5,(5,5))
print(Z)
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[1 4 0 2 3]
 [0 0 1 1 1]
 [2 1 0 1 4]
 [4 3 4 3 4]
 [2 3 4 3 3]]
[[[[1 4 0]
   [0 0 1]
   [2 1 0]]

  [[4 0 2]
   [0 1 1]
   [1 0 1]]

  [[0 2 3]
   [1 1 1]
   [0 1 4]]]


 [[[0 0 1]
   [2 1 0]
   [4 3 4]]

  [[0 1 1]
   [1 0 1]
   [3 4 3]]

  [[1 1 1]
   [0 1 4]
   [4 3 4]]]


 [[[2 1 0]
   [4 3 4]
   [2 3 4]]

  [[1 0 1]
   [3 4 3]
   [3 4 3]]

  [[0 1 4]
   [4 3 4]
   [4 3 3]]]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
Z [i、j] == Z [j、i]となるような2D配列サブクラスを作成します

#スーパークラスの作り方とかよう勉強

In [116]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9  0  6 15 13]
 [ 0  6  5 15 10]
 [ 6  5  1 42 11]
 [15 15 42  9 14]
 [13 10 11 14  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
形状（n、n）を持つp行列のセットと、形状（n、1）を持つpベクトルのセットについて考えてみます。 p行列積の合計を一度に計算する方法は？ （結果の形状は（n、1））

In [130]:
n = 2
p = np.random.randint(0,5,(2,n,n))
print(p)
print(p.shape)

b = np.random.randint(0,5,(2,n,1))
print(b)
print(b.shape)

np.tensordot(p, b, axes = [[0,2],[0,1]])

[[[1 1]
  [0 3]]

 [[3 4]
  [2 0]]]
(2, 2, 2)
[[[3]
  [1]]

 [[0]
  [0]]]
(2, 2, 1)


array([[4],
       [3]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
16x16配列を考えてみましょう。ブロック合計（ブロックサイズは4x4）を取得する方法は？
参考URL  
https://qiita.com/nyandora/items/0fac6e307edc16c3cb91

In [131]:
answer(87)

# Author: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)


In [139]:
z = np.ones((16,16))
print(z)

k = 4
# reduceat(単一の軸上で指定されたスライスを使用して（ローカル）縮小を実行します。)
s1 = np.add.reduceat(z, np.arange(0, z.shape[0],k), axis=0)
print(s1)
s2 = np.add.reduceat(s1,np.arange(0, s1.shape[1],k), axis=1)

print(s2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4

#### 88. How to implement the Game of Life using numpy arrays? (★★★)
numpy配列を使用してGameof Lifeを実装するにはどうすればよいですか？  
Game of Lifeのwiki  
https://ja.wikipedia.org/wiki/%E3%83%A9%E3%82%A4%E3%83%95%E3%82%B2%E3%83%BC%E3%83%A0

In [200]:
#意味不明

In [199]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

a = np.random.randint(0,2,(5,5))
print(a)

for i in range(10): Z = iterate(a)
print(Z)

[[1 1 1 1 1]
 [1 0 0 1 1]
 [0 1 1 0 0]
 [0 1 1 0 1]
 [1 1 1 1 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)
配列のn個の最大値を取得する方法

In [203]:
a = np.random.randint(0,10,10)
print(a)

a.max()

[4 5 8 6 8 5 8 8 4 5]


8

In [206]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
%timeit Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[   0    1    2 ... 9997 9998 9999]
[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)