In [1]:
s = 3
g = 19

x = (g-s)*60
print(x)

a = (25 + 5)*4 + 20
print(a)

z = x/a

h = z - z%1
print(h*(25*4))

# 1.np x2
# 2.data x 2
# 3.自然言語 x10
# 4.画像処理 x10
# 5.kaggle*4 本 x 10
# 6.atcoder 本 x 10

960
140
600.0


# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
pip install mdutils

Note: you may need to restart the kernel to use updated packages.


In [3]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)
numpyバージョンと構成を印刷します

#### 3. Create a null vector of size 10 (★☆☆)
サイズ10のヌルベクトルを作成します

#### 4. How to find the memory size of any array (★☆☆)
配列のメモリサイズを見つける方法

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
コマンドラインからnumpyadd関数のドキュメントを取得するにはどうすればよいですか？

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
サイズ10のヌルベクトルを作成しますが、5番目の値は1です

In [5]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)
10から49の範囲の値を持つベクトルを作成します


In [6]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [7]:
np.arange(10,49)[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [9]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [10]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)
ランダムな値で3x3x3配列を作成します

In [11]:
np.random.randn(3,3,3)

array([[[ 0.58890561, -2.80444521,  0.05240419],
        [-0.48205905,  0.60701189, -0.64831621],
        [ 0.39101966, -0.05967449,  1.68115563]],

       [[-0.85537935,  1.83993007, -1.44432988],
        [-1.32831268, -0.93889513,  1.00295911],
        [-0.14169373,  0.31306903, -0.62656262]],

       [[ 0.2772351 ,  1.12998102,  1.35550401],
        [-0.04280329,  0.32445682,  1.02827348],
        [-0.43075242,  0.0383895 , -1.06452132]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
ランダムな値で10x10の配列を作成し、最小値と最大値を見つけます


In [12]:
a = np.random.random((10,10))
a.max()

0.9918255514463274

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)
サイズ30のランダムなベクトルを作成し、平均値を見つけます

In [13]:
a = np.random.random(10)
a.mean()

0.6097939493286411

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
境界に1、内側に0の2次元配列を作成します


In [14]:
a = np.ones((5,5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
既存の配列の周りに境界線（0で埋められる）を追加するにはどうすればよいですか？

In [15]:
a = np.ones((5,5))
np.pad(a,(1,1))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
次の式の結果は何ですか？

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [16]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
対角のすぐ下に値1、2、3、4の5x5行列を作成します

In [17]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
8x8マトリックスを作成し、チェッカーボードパターンで塗りつぶします


In [18]:
a = np.zeros((8,8))

a[::2, 1::2] = 1
a[1::2, ::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
（6,7,8）形状配列を考えてみましょう。100番目の要素のインデックス（x、y、z）は何ですか？


In [19]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
タイル関数を使用してチェッカーボード8x8マトリックスを作成します

In [20]:
a = np.array([[0,1],[1,0]])

np.tile(a,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)
5x5のランダム行列を正規化する

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
色を4つの符号なしバイト（RGBA）として記述するカスタムdtypeを作成します


In [21]:
color = np.dtype([("r", float),
                  ("g", float),
                  ("b", float),
                  ("a", float)])
color

dtype([('r', '<f8'), ('g', '<f8'), ('b', '<f8'), ('a', '<f8')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)
5x3行列に3x2行列を掛けます（実際の行列の積）

In [22]:
a = np.ones((5,3))
b = np.ones((3,2))
a@b

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)
1D配列が与えられた場合、3から8までのすべての要素を適切に無効にします。

In [23]:
a = np.arange(9)
a[(3 <= a) & (a < 8)] *= -1
a

array([ 0,  1,  2, -3, -4, -5, -6, -7,  8])

#### 26. What is the output of the following script? (★☆☆)
次のスクリプトの出力は何ですか？

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [24]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


numpy.sumとsumの挙動の違い

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
整数ベクトルZを考えてみましょう。これらの式のどれが有効ですか？

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [25]:
Z = np.array([1,2,3])

print(Z**Z)
print(2 << Z >>2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z) エラーが出る

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions?
次の式の結果は何ですか？

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [26]:
print(np.array(0) / np.array(0))

print(np.array(0) // np.array(0))

print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


<ipython-input-26-72dab2b1b7c8>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-26-72dab2b1b7c8>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)
フロート配列をゼロから丸める方法は？


#### 30. How to find common values between two arrays? (★☆☆)
2つの配列間で共通の値を見つける方法は？

In [27]:
a = np.random.randint(0,3,5)
b = np.random.randint(0,3,5)

np.intersect1d(a,b)

array([0, 1])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
すべてのnumpy警告を無視する方法（非推奨）？

#### 32. Is the following expressions true? (★☆☆)
次の表現は本当ですか？
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [28]:
print(np.sqrt(-1))
np.emath.sqrt(-1)

nan


<ipython-input-28-ddc7bbd93843>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)
昨日、今日、明日の日付を取得するにはどうすればよいですか？

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)
2016年7月に対応するすべての日付を取得するにはどうすればよいですか？

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
（（A + B）*（-A / 2））をその場で（コピーなしで）計算する方法は？

In [29]:
a = np.ones(4)*1
b = np.ones(4)*2

np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a, out=a)
np.multiply(b, a)

array([-1.5, -1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)
4つの異なる方法を使用して、正の数のランダム配列の整数部分を抽出します

In [31]:
a = np.random.uniform(1,5,5)
print(a)
print(a - a%1)
print(a//1)
print(a.astype(int))
print(np.floor_divide(a,1))

[4.56197656 1.77076077 4.15603605 2.41976624 3.27856162]
[4. 1. 4. 2. 3.]
[4. 1. 4. 2. 3.]
[4 1 4 2 3]
[4. 1. 4. 2. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)
0から4の範囲の行値を持つ5x5行列を作成します

In [32]:
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [33]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
10個の整数を生成し、それを使用して配列を作成するジェネレーター関数について考えてみます。

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
0から1の範囲の値を持つサイズ10のベクトルを作成し、両方を除外します

In [34]:
np.linspace(0,1,11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)
サイズ10のランダムなベクトルを作成し、並べ替えます


In [35]:
a = np.random.randint(1,10,10)
np.sort(a)

array([1, 2, 4, 5, 5, 6, 8, 8, 8, 8])

#### 41. How to sum a small array faster than np.sum? (★★☆)
np.sumよりも速く小さな配列を合計する方法は？

In [36]:
a = np.ones(10)
%timeit np.add.reduce(a)

%timeit np.sum(a)

%timeit sum(a)

473 ns ± 1.82 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.48 µs ± 25.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.46 µs ± 12.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)
2つのランダム配列AとBを検討し、それらが等しいかどうかを確認します

In [37]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)

#完全一致
print(np.all(a==b))

#多少の猶予あり一致
print(np.allclose(a,b))

False
False


#### 43. Make an array immutable (read-only) (★★☆)
配列を不変にする（読み取り専用）

In [38]:
a = np.arange(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
デカルト座標を表すランダムな10x2行列を考え、それらを極座標に変換します

In [ ]:
import matplotlib.pyplot as plt


z = np.random.random((10, 2))
x,y = z[:,0],z[:,1]

radii = np.sqrt(x**2 + y**2)
theta = np.arctan2(y,x)
    
# 極座標系グラフ
ax2 = plt.subplot(1,1,1,polar=True)
ax2.scatter(theta,radii)
ax2.set_rmax(1)
ax2.grid(True)

plt.show()

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
サイズ10のランダムベクトルを作成し、最大値を0に置き換えます

In [ ]:
a = np.random.random(10)
a[np.argmax(a)] = 0
a

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)
[0,1] x [0,1]領域をカバーするx座標とy座標を持つ構造化配列を作成します

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
print(Z)

Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
XとYの2つの配列が与えられた場合、コーシー行列Cを作成します（Cij = 1 /（xi -yj））


In [ ]:
x = np.arange(3)
y = x + 0.5

# cの行列を作成
c = 1.0/np.subtract.outer(x,y)

# cの行列式
np.linalg.det(c)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
各スカラー型numpyの表現可能な最小値と最大値を出力します

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

#### 49. How to print all the values of an array? (★★☆)
配列のすべての値を出力するにはどうすればよいですか？

In [ ]:
import numpy

a = numpy.arange(10000)

# 全て表示する
# numpy.set_printoptions(threshold=float("inf"))

# デフォルト値に戻す
# numpy.set_printoptions(threshold=1000)

print(a)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
ベクトル内で（特定のスカラーに）最も近い値を見つける方法は？


In [ ]:
a = np.random.random(10)
print(a)

b = 0.5
print(b)

%timeit a[abs(a - b).argmin()]

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)
位置（x、y）と色（r、g、b）を表す構造化配列を作成します

In [40]:
nvaaa

NameError: name 'nvaaa' is not defined

In [41]:
z = np.zeros(10,[("position", [("x", float),
                               ("y", float)]),
                 ("color",    [("r", float),
                               ("g", float),
                               ("b", float)])])
z

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
座標を表す形状（100,2）のランダムベクトルを考え、ポイントごとの距離を見つけます


In [42]:
from scipy.spatial import distance

z = np.random.random((10,2))
distance.cdist(z,z)

array([[0.        , 0.60029285, 0.41303289, 0.4789413 , 0.36100774,
        0.46314668, 0.46442319, 0.30591257, 0.3332074 , 0.25335691],
       [0.60029285, 0.        , 0.38033568, 0.2953144 , 0.54866021,
        0.80451603, 1.02372772, 0.89654991, 0.68260518, 0.42078498],
       [0.41303289, 0.38033568, 0.        , 0.10029656, 0.60614236,
        0.4313363 , 0.71497239, 0.70704129, 0.67177835, 0.4224162 ],
       [0.4789413 , 0.2953144 , 0.10029656, 0.        , 0.61530518,
        0.52969587, 0.81181962, 0.78118195, 0.7012418 , 0.43542143],
       [0.36100774, 0.54866021, 0.60614236, 0.61530518, 0.        ,
        0.81363911, 0.79419748, 0.50552747, 0.15368157, 0.18373535],
       [0.46314668, 0.80451603, 0.4313363 , 0.52969587, 0.81363911,
        0.        , 0.39457614, 0.59867622, 0.79502843, 0.66244869],
       [0.46442319, 1.02372772, 0.71497239, 0.81181962, 0.79419748,
        0.39457614, 0.        , 0.35520474, 0.70359178, 0.71749483],
       [0.30591257, 0.89654991, 0.7070412

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
float（32ビット）配列を整数（32ビット）に変換するにはどうすればよいですか？

In [43]:
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)

Y = Z.view(np.int32)
print(Y)

Y[:] = Z
print(Y)

#理解が出来ない。 astpyeでいいのでは？

[39.258305 98.9896   53.927227 31.701298 55.056583 58.32125  97.898605
 60.179176 76.74656  99.072105]
[1109198977 1120271021 1113044347 1107139650 1113340401 1114196214
 1120128022 1114683258 1117355581 1120281835]
[39 98 53 31 55 58 97 60 76 99]


#### 54. How to read the following file? (★★☆)
次のファイルの読み方は？
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [44]:
from io import StringIO

a = StringIO('''
             1, 2, 3, 4, 5
             6,  ,  , 7, 8
              ,  , 9,10,11
              ''')

np.genfromtxt(a, delimiter=",", dtype=int8)

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]], dtype=int8)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
numpy配列の列挙に相当するものは何ですか？

In [45]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### ２次元ガウス配列(要学習）


$確率密度関数	𝑓(𝑋)=\frac{1}{\sqrt2πσ^2}exp[−\frac{(𝑥−μ)^2}{2σ^2}]$  
$期待値（平均）	𝐸(𝑋)=μ$  
$分散	𝑉(𝑋)=σ^2$  
$標準偏差	𝑆𝐷(𝑋)=σ$

In [46]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)

sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)
p要素を2D配列にランダムに配置するにはどうすればよいですか？

In [47]:
n = 5
p = 2
z = np.zeros((n,n))

x = np.random.choice(range(n*n),p,replace=False)
print(x)

np.put(z, x, 1)
z

[15 13]


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)  
行列の各行の平均を減算します

In [48]:
a = np.random.randint(0,10,(2,4))
print(a)

print(a - a.mean(axis=1,keepdims=True))

[[4 8 4 7]
 [6 0 9 1]]
[[-1.75  2.25 -1.75  1.25]
 [ 2.   -4.    5.   -3.  ]]


#### 59. How to sort an array by the nth column? (★★☆)  
n番目の列で配列を並べ替える方法は？

In [49]:
a = np.random.randint(0,10,(5,5))
n = 2
print(a)

a[a[:,n].argsort()]

[[2 6 3 0 6]
 [5 3 7 3 1]
 [0 9 0 9 7]
 [4 4 8 4 8]
 [5 5 3 5 9]]


array([[0, 9, 0, 9, 7],
       [2, 6, 3, 0, 6],
       [5, 5, 3, 5, 9],
       [5, 3, 7, 3, 1],
       [4, 4, 8, 4, 8]])

#### 61. Find the nearest value from a given value in an array (★★☆)  
配列内の指定された値から最も近い値を見つけます

In [50]:
a = np.random.rand(3,3)
print(a)
z = np.random.rand(1)
print(z)

# np.absは絶対値をとる、一番差が小さいインデックスを抽出
index = np.abs(z - a).argmin()

# np.flatはイテレータを返す
a.flat[index]

[[0.32387169 0.85061851 0.94164534]
 [0.88531846 0.27867659 0.89566092]
 [0.71100136 0.92574492 0.21913225]]
[0.26887107]


0.27867659158133906

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)  
形状が（1,3）と（3,1）の2つの配列を考えると、イテレーターを使用してそれらの合計を計算する方法は？

In [51]:
# for以降、理解が出来ない

In [52]:
A = np.arange(3).reshape(3,1)
print(A)
B = np.arange(3).reshape(1,3)
print(B)

it = np.nditer([A,B,None])
print(it)

for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)  
name属性を持つ配列クラスを作成します

In [64]:
dddd

NameError: name 'dddd' is not defined

In [65]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10))
print (Z.name)

no name


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)  
与えられたベクトルを考えてみましょう。2番目のベクトルでインデックス付けされた各要素に1を追加する方法（インデックスの繰り返しに注意してください）？

In [66]:
z = np.ones(10)
print(z)
i = np.random.randint(0,len(z), 20)
print(i)
z += np.bincount(i, minlength=len(z))
print(z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[3 7 6 6 8 5 2 7 6 5 5 5 5 7 1 8 8 2 7 2]
[1. 2. 4. 2. 1. 6. 4. 5. 4. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)  
インデックスリスト（I）に基づいて、ベクトル（X）の要素を配列（F）に累積する方法は？

In [67]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)
（dtype = ubyte）の（w、h、3）画像を考慮して、一意の色の数を計算します

#理解不能

In [68]:
w,h = 16,16
i = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
f = i[...,0]*256*256 + i[...,1]*256 + i[...,2]
n = len(np.unique(f))
print(np.unique(i))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
4次元配列を考えると、最後の2つの軸の合計を一度に取得するにはどうすればよいですか？

In [72]:
random.seed(0)
A = np.random.randint(0,5,(2,2,2,2))
print(A)
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-1,-2))
print("合計\n",sum)

[[[[4 0]
   [3 3]]

  [[3 1]
   [3 2]]]


 [[[4 0]
   [0 4]]

  [[2 1]
   [0 1]]]]
合計
 [[10  9]
 [ 8  4]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)  
1次元のベクトルDを考えると、サブセットインデックスを記述する同じサイズのベクトルSを使用して、Dのサブセットの平均を計算する方法は？

In [81]:
aaa

NameError: name 'aaa' is not defined

In [82]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.49865202 0.47958017 0.62583388 0.61586389 0.47239415 0.56749014
 0.33153623 0.50934107 0.60491391 0.55474409]


#### 69. How to get the diagonal of a dot product? (★★★)  
内積の対角線を取得するにはどうすればよいですか？

In [87]:
a = np.random.randint(0,3,(2,2))
b = np.random.randint(0,3,(2,2))
print(a)
print(b)
c = a@b
print(c)
print(np.diag(c))

[[0 0]
 [1 0]]
[[0 1]
 [2 2]]
[[0 0]
 [0 1]]
[0 1]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
ベクトル[1、2、3、4、5]について考えてみましょう。各値の間に、3つの連続するゼロがインターリーブされた新しいベクトルを作成する方法を教えてください。

In [91]:
a = [1, 2, 3, 4, 5]
nz = 3
z0 = np.zeros(len(a) + (len(a)-1)*(nz))
print(z0)
z0[::nz+1] = a
print(z0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
次元（5,5,3）の配列を考えてみましょう。次元（5,5）の配列でそれを多重化する方法は？

In [93]:
aaaa

NameError: name 'aaaa' is not defined

In [92]:
A = np.ones((5,5,3))
print(A)
B = 2*np.ones((5,5))
print(B)
print(B[:,:,None])
print(A * B[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]]
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)
配列の2つの行を交換する方法は？

In [96]:
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

# 列の入れ替え
A[:, [1,2,3,4,0]]

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 6,  7,  8,  9,  5],
       [ 1,  2,  3,  4,  0],
       [11, 12, 13, 14, 10],
       [16, 17, 18, 19, 15],
       [21, 22, 23, 24, 20]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
（頂点が共有されている）10個の三角形を表す10個のトリプレットのセットを検討し、すべての三角形を構成する一意の線分のセットを見つけます。


In [97]:
# 理解不能
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 23) ( 4, 24) ( 6, 71) ( 6, 81) ( 7,  8) ( 7, 13) ( 8, 13) ( 8, 89)
 ( 8, 99) (16, 56) (16, 60) (20, 25) (20, 54) (22, 79) (22, 80) (23, 24)
 (23, 57) (23, 97) (25, 54) (30, 49) (30, 87) (49, 87) (56, 60) (57, 97)
 (66, 84) (66, 89) (71, 81) (79, 80) (84, 89) (89, 99)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
bincountに対応するソートされた配列Cが与えられた場合、np.bincount（A）== Cとなるような配列Aを生成するにはどうすればよいですか？

In [102]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)


print(np.arange(len(C)))
# numpy.repeat(a, n) はスカラーや配列 a の各要素を n 回 繰り返す 配列を生成します。
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[0 1 2 3 4 5 6]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)
配列上のスライディングウィンドウを使用して平均を計算するにはどうすればよいですか？


In [103]:
aaaa:]
    

SyntaxError: unmatched ']' (<ipython-input-103-ddd09eebfa02>, line 1)

In [ ]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    # np.cumsum()で累積和を取得
    ret = np.cumsum(a, dtype=float)
    print(ret)
    print(ret[n:])
    print(ret[:-n])
    # スライド幅 -1 の幅を算出（−１は重複している値)
    ret[n:] = ret[n:] - ret[:-n]
    print(ret[n:])
    print(ret[n - 1:])
    # 重複して削除された値を補填して平均化
    return ret[n - 1:] / n
Z = np.arange(5)
print(Z)
print(moving_average(Z, n=3))

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
1次元配列Zを考え、最初の行が（Z [0]、Z [1]、Z [2]）で、後続の各行が1ずつシフトされる2次元配列を作成します（最後の行は（Z [ -3]、Z [-2]、Z [-1]）


In [133]:
aaa

NameError: name 'aaa' is not defined

In [134]:
from numpy.lib.stride_tricks import as_strided

def roll(a, window):
    # shapeサイズを求める>>>(8,3)
    shape = (a.size - window + 1, window)
    # stride_tricks.as_stridedの引数strides（スキップ幅)は、byte単位で計算するので、aのbyte数を抽出する。
    strides = (a.itemsize, a.itemsize)
    return as_strided(a, shape=shape, strides=strides)

roll(np.arange(10),3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
ブール値を無効にする方法、またはフロートの符号をインプレースで変更する方法は？

In [112]:
aaa


NameError: name 'aaa' is not defined

In [113]:
# Author: Nathaniel J. Smith

#ブール値の無効（否定）
Z = np.random.randint(0,2,100)
z = np.logical_not(Z, out=Z)
print(Z)
print(z)

#インプレース
A = np.random.uniform(-1.0,1.0,100)
a = np.negative(Z, out=Z)
print(A)
print(a)

[1 1 0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0 1 1 0 0 0 0
 0 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0 1 1 1 0 0 0
 1 0 0 1 0 1 0 0 1 1 0 0 1 0 1 1 1 0 0 0 0 0 1 0 1 1]
[1 1 0 0 1 0 1 1 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 0 0 1 0 0 1 1 0 0 0 0
 0 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 1 1 1 1 0 1 1 1 0 0 0
 1 0 0 1 0 1 0 0 1 1 0 0 1 0 1 1 1 0 0 0 0 0 1 0 1 1]
[-0.45749585 -0.19241452 -0.20037572  0.34276696 -0.31056375  0.42753374
  0.2783738  -0.20167771 -0.13647974  0.2290554  -0.85991562  0.64481348
  0.30684232  0.45268493  0.073846   -0.77904578 -0.18992877 -0.18925283
 -0.35791402 -0.94009935  0.47450849 -0.78043108  0.21261627  0.40643499
  0.26957265  0.9182845  -0.79340369  0.73433432 -0.94161953  0.06983371
 -0.19151276  0.04836772 -0.26980025 -0.61886617 -0.96175421  0.03629963
  0.68555373 -0.25356809 -0.55427236 -0.83893599 -0.82937815 -0.55720711
 -0.79997188 -0.4699206  -0.86770108 -0.86879027  0.71255236 -0.67575948
  0.1193

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
線（2d）と点pを表す2組の点P0、P1を考えてみましょう。pから各線i（P0 [i]、P1 [i]）までの距離を計算する方法は？


点と直線の公式  
https://okimath.com/tento

In [119]:
# 理解不能

aaaaa

NameError: name 'aaaaa' is not defined

In [120]:
p = np.array([[1, 2]])
P0 = np.array([[3, 5]])
P1 = np.array([[3, -3]])

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    print(U)
    U = U.reshape(len(U),1)
    print(U)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

print(distance(P0, P1, p))

[0.375]
[[0.375]]
[2.]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)
線（2d）を表す2組の点P0、P1と1組の点Pを考えてみましょう。各点j（P [j]）から各線i（P0 [i]、P1 [i]）までの距離を計算する方法は？


In [122]:
aaaa

NameError: name 'aaaa' is not defined

In [124]:
p = np.random.randint(-10,10,(10,2))
print(p)

print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[  1  -7]
 [ -2   9]
 [  4 -10]
 [-10  -8]
 [  1  -5]
 [ -8  -3]
 [  2   1]
 [  9  -9]
 [  6   8]
 [  8   4]]
[ 0.29141171 -0.39415796  0.52162079  0.87818716  0.19708954 -0.68927504
  2.1149508   0.55518203  1.25609227  0.38009791]
[[ 0.29141171]
 [-0.39415796]
 [ 0.52162079]
 [ 0.87818716]
 [ 0.19708954]
 [-0.68927504]
 [ 2.1149508 ]
 [ 0.55518203]
 [ 1.25609227]
 [ 0.38009791]]
[ 0.37025769  3.09141769 -0.76705545  0.47723582  0.80394879  9.25550098
 -0.98811472  0.69438745 -1.21339187  0.14914188]
[[ 0.37025769]
 [ 3.09141769]
 [-0.76705545]
 [ 0.47723582]
 [ 0.80394879]
 [ 9.25550098]
 [-0.98811472]
 [ 0.69438745]
 [-1.21339187]
 [ 0.14914188]]
[ 0.72040193 -1.62214194  0.66611857  1.24371235 -0.0640855  -2.20472881
  2.34153915  0.70283203  1.74996311  0.61810885]
[[ 0.72040193]
 [-1.62214194]
 [ 0.66611857]
 [ 1.24371235]
 [-0.0640855 ]
 [-2.20472881]
 [ 2.34153915]
 [ 0.70283203]
 [ 1.74996311]
 [ 0.61810885]]
[-1.75032431  2.02451923  1.04796034 -0.42937078  0.83563824 -2.913

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
任意の配列を検討し、固定された形状で特定の要素を中心とするサブパーツを抽出する関数を記述します（必要に応じて塗りつぶし値のあるパッド）

In [125]:
# 理解は出来たが難しい

In [126]:
Z = np.random.randint(0,3,(10,10))
print(Z)
print()
shape = (5,5)
fill  = 0
position = (1,1)

# Rが新しく作るパディング
# Zは元の配列

R  = np.ones(shape, dtype=Z.dtype)*fill
# >> 0の(5,5)配列
P  = np.array(list(position)).astype(int)
# >> [1 1]
Rs = np.array(list(R.shape)).astype(int)
# >> [5 5]
Zs = np.array(list(Z.shape)).astype(int)
# >> [10 10]


R_start = np.zeros((len(shape),)).astype(int)
# >> [0 0]
R_stop  = np.array(list(shape)).astype(int)
# >> [5,5]
Z_start = (P-Rs//2)
# >> [-1 -1]
Z_stop  = (P+Rs//2)+Rs%2
# >> [4 4]

# minimum()、maximun()は、引数に渡した2つの配列の各要素のうち、値が小さい方(大きい方)を取得する関数です。
R_start = (R_start - np.minimum(Z_start,0)).tolist()
# >> [1,1]
Z_start = (np.maximum(Z_start,0)).tolist()
# >> [0,0]
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
# >> [5,5]
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
# >> [4,4]

#組み込み関数slice()を使うとスライスオブジェクトを生成できる。同じ位置の要素を繰り返し取得したい場合はスライスオブジェクトを一度生成しておくだけでよいので便利。
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(R)

[[1 1 1 2 2 0 0 1 1 0]
 [1 0 0 0 2 1 2 1 2 1]
 [1 0 2 2 1 2 1 1 0 1]
 [2 0 1 0 0 1 2 1 1 1]
 [1 1 2 0 2 1 0 0 0 2]
 [2 2 1 2 2 2 0 0 1 0]
 [1 0 1 1 0 0 2 2 1 1]
 [1 0 0 2 0 1 2 0 1 0]
 [0 0 1 1 0 1 0 2 1 0]
 [0 0 2 1 0 0 0 1 2 2]]

[[0 0 0 0 0]
 [0 1 1 1 2]
 [0 1 0 0 0]
 [0 1 0 2 2]
 [0 2 0 1 0]]


<ipython-input-126-35f4714c35ad>:43: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
配列Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]を考えてみましょう。配列を生成する方法は、R = [[1,2,3、 4]、[2,3,4,5]、[3,4,5,6]、...、[11,12,13,14]]？

In [136]:
aaa

NameError: name 'aaa' is not defined

In [137]:
Z = np.arange(1,15,dtype=np.uint32)
R = as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)
行列の階数を計算する

In [141]:
aaa

NameError: name 'aaa' is not defined

In [ ]:
a = np.random.randint(1,4,(3,3))
print(a)

np.linalg.matrix_rank(a)

#### 83. How to find the most frequent value in an array?
配列内で最も頻度の高い値を見つける方法


In [148]:
aaaa

[0 0 0 2 3 1 4 3 4 3]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


TypeError: Cannot cast array data from dtype('float64') to dtype('int64') according to the rule 'safe'

In [ ]:
a = np.random.randint(0,10,30)
print(a)

a[np.bincount(a).argmax()]

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
ランダムな10x10行列からすべての隣接する3x3ブロックを抽出します


In [150]:
ddd

NameError: name 'ddd' is not defined

In [151]:
Z = np.random.randint(0,5,(5,5))
print(Z)
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[1 0 1 2 3]
 [0 0 1 1 1]
 [4 2 1 4 0]
 [2 4 0 3 3]
 [2 4 4 0 3]]
[[[[1 0 1]
   [0 0 1]
   [4 2 1]]

  [[0 1 2]
   [0 1 1]
   [2 1 4]]

  [[1 2 3]
   [1 1 1]
   [1 4 0]]]


 [[[0 0 1]
   [4 2 1]
   [2 4 0]]

  [[0 1 1]
   [2 1 4]
   [4 0 3]]

  [[1 1 1]
   [1 4 0]
   [0 3 3]]]


 [[[4 2 1]
   [2 4 0]
   [2 4 4]]

  [[2 1 4]
   [4 0 3]
   [4 4 0]]

  [[1 4 0]
   [0 3 3]
   [4 0 3]]]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
Z [i、j] == Z [j、i]となるような2D配列サブクラスを作成します

#スーパークラスの作り方を復習

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

s = np.random.randint(0,10,(5,5))
S = symetric(s)
S[2,3] = 42
print(S)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
形状（n、n）を持つp行列のセットと、形状（n、1）を持つpベクトルのセットについて考えてみます。 p行列積の合計を一度に計算する方法は？ （結果の形状は（n、1））

テンソル積の理解_参考  
https://qiita.com/nyandora/items/0fac6e307edc16c3cb91

In [ ]:
n = 2
p = np.random.randint(0,5,(2,n,n))
print(p)
print()
b = np.random.randint(0,5,(2,n,1))
print(b)

# 行列aの1次元、3次元の中間行列*ベクトルbの3次元、２次元で積をとる。
np.tensordot(p, b, axes = [[0,2],[0,1]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
16x16配列を考えてみましょう。ブロック合計（ブロックサイズは4x4）を取得する方法は？  

### ヒント  

ufunc.reduceat（配列、インデックス、軸= 0、dtype =なし、out =なし）  
単一の軸上で指定されたスライスを使用して（ローカル）縮小を実行します。  
https://numpy.org/doc/stable/reference/generated/numpy.ufunc.reduceat.html

In [ ]:
z = np.ones((16,16))
print(z)

k = 4
# reduceat(単一の軸上で指定されたスライスを使用して（ローカル）縮小を実行します。)
s1 = np.add.reduceat(z, np.arange(0, z.shape[0],k), axis=0)
print(s1)
s2 = np.add.reduceat(s1,np.arange(0, s1.shape[1],k), axis=1)

print(s2)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)
numpy配列を使用してGameof Lifeを実装するにはどうすればよいですか？  
Game of Lifeのwiki  
https://ja.wikipedia.org/wiki/%E3%83%A9%E3%82%A4%E3%83%95%E3%82%B2%E3%83%BC%E3%83%A0

In [ ]:
#意味不明

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

a = np.random.randint(0,2,(5,5))
print(a)

for i in range(10): Z = iterate(a)
print(Z)

#### 89. How to get the n largest values of an array (★★★)
配列のn個の最大値を取得する方法

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
%timeit Z[np.argsort(Z)[-n:]]

# Fast
%timeit Z[np.argpartition(-Z,n)[:n]]

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)  
任意の数のベクトルを指定して、デカルト積を作成します（すべてのアイテムのすべての組み合わせ）


In [ ]:
from sklearn.utils.extmath import cartesian
cartesian(([1, 2, 3], [4, 5], [6, 7]))

#### 91. How to create a record array from a regular array? (★★★)  
通常の配列からレコード配列を作成するにはどうすればよいですか？


In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])


R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

In [ ]:
# 新しく作る方法
mydtype = np.dtype("i4,i8")
mydtype.names = ("x","y")
N = 10

a = np.zeros(N, dtype = mydtype)
a["x"] = np.random.randint(0,10,N)
a["y"] = np.random.randint(-10,0,N)

print(a["x"])
print(a["x"])

b = np.lexsort((a["x"],a["y"]))

print(a[b])

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)  
大きなベクトルZを考え、3つの異なる方法を使用してZを3の累乗で計算します。


In [ ]:
x = np.random.rand(int(5e1))

%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)
%timeit x**3
%timeit np.power(x,3)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)  
形状（8,3）と（2,2）の2つの配列AとBについて考えてみます。 Bの要素の順序に関係なく、Bの各行の要素を含むAの行を見つける方法は？

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A)
print("--------------------")
print(B)
print()

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)  
10x3の行列を考慮して、値が等しくない行を抽出します（例：[2,2,3]）

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# すべてのdtypeの配列（文字列配列とレコード配列を含む）のソリューション
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# 数値配列のみのソリューションは、Zの任意の数の列で機能します
# U = Z[Z.max(axis=1) != Z.min(axis=1),:]
# print(U)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)
intのベクトルを行列のバイナリ表現に変換します


In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

# I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
# print(np.unpackbits(I[:, np.newaxis], axis=1))

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)
2次元配列が与えられた場合、一意の行を抽出する方法は？

In [ ]:
a = np.random.randint(0,2,(6,3))
print(a)

np.unique(a,axis=0)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)
2つのベクトルAとBを考慮して、inner、outer、sum、およびmul関数に相当するeinsumを記述します。

In [ ]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

# np.sum(a)
z = np.einsum("i->", a)
print(z)

# a * b
z = np.einsum("i,i->i", a, b)
print(z)

# np.inner(a, b)
z = np.einsum("i,i", a, b)
print(z)

# np.outer(a, b)
z = np.einsum("i,j->ij", a, b)
print(z)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?
2つのベクトル（X、Y）で記述されたパスを考慮して、等距離のサンプルを使用してパスをサンプリングする方法


In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)
整数nと2D配列Xが与えられた場合、Xから、n度の多項分布からの描画として解釈できる行、つまり整数のみを含み、合計がnになる行を選択します。

In [ ]:
# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])

n = 4

# func.reduce : 1つの軸に沿ってufuncを適用することにより、配列の次元を1つ減らす。
# logical_and : 引数１と引数２の真理値を要素ごとに計算する。
# np.mod : 配列の剰余。

# 行毎に1で割り切れるか（整数)確認を行っている。
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1) 
# 行毎の合計を計算し、してされた整数との比較。
M &= (X.sum(axis=-1) == n) 
print(X[M])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)
1D配列Xの平均のブートストラップされた95％信頼区間を計算します（つまり、配列の要素をN回置換して再サンプリングし、各サンプルの平均を計算してから、平均のパーセンタイルを計算します）。

In [ ]:
X = np.random.randn(100) # random 1D array


N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))

means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)