# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
Z = np.zeros((10,10))
print(f"{Z.size * Z.itemsize} bytes")

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
a = np.zeros(10)
a[5] = 1
a

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
a = np.arange(10,50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
np.random.random((3,3,3))

array([[[0.51060594, 0.93744188, 0.10160683],
        [0.73650383, 0.00879537, 0.36193554],
        [0.20753843, 0.92128259, 0.6001696 ]],

       [[0.6615168 , 0.46832323, 0.88311218],
        [0.01087703, 0.49562249, 0.65664234],
        [0.92097823, 0.67825481, 0.68570757]],

       [[0.3450825 , 0.3756155 , 0.56002815],
        [0.40183143, 0.67974935, 0.76583548],
        [0.69953771, 0.01352046, 0.59592836]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
a = np.random.random((10,10))
print(a.max(), a.min())

0.99395362629393 0.02148052210340723


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
np.random.random(30).mean()

0.5053025825190045

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
a = np.ones((5,5))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
a = np.ones((5,5))
np.pad(a,(1,1))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
a = np.zeros((8,8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [21]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
a = np.array([[0,1],[1,0]])
np.tile(a,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
a = np.random.random((5,5))

(a - a.mean()) / ((a.max()) - (a.min()))

array([[ 0.12549175, -0.09920125, -0.09753472,  0.03617198, -0.22573622],
       [-0.56430018,  0.2518881 ,  0.3955786 ,  0.39783144,  0.34375814],
       [-0.02398715,  0.28208525,  0.27495428, -0.05703173,  0.21974133],
       [-0.44397727, -0.60216856,  0.07681442,  0.38782502, -0.34705455],
       [-0.43220705, -0.00178896, -0.14633626, -0.13310735,  0.38229094]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
np.ones((5,3)) @ np.ones((3,2))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
a = np.arange(0,11)
a[(a > 3) & (a < 8)] *= -1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


numpy.sumとsumの挙動の違い

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
Z = np.array([1,2,3])

print(Z**Z)
print(2 << Z >>2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z) エラーが出る

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0))

print(np.array(0) // np.array(0))

print(np.array([np.nan]).astype(int).astype(float))

nan
0
[0.]


<ipython-input-29-72dab2b1b7c8>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-29-72dab2b1b7c8>:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
np.random.random(1).round()

array([0.])

#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
a = np.random.randint(1,5,5)
b = np.random.randint(1,5,5)

print("a:",a)
print("b:",b)
print(intersect1d(a,b))

a: [4 4 4 2 1]
b: [2 4 3 1 3]
[1 2 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
defaults = np.seterr(all="ignore")
defaults

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [33]:
np.seterr(**defaults)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

nan
1j


<ipython-input-34-54f6324019e1>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [35]:
today = np.datetime64("today")
tomorrow = today - np.timedelta64(-1)
yesterday = today - np.timedelta64(1)
yesterday

numpy.datetime64('2021-03-27')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [36]:
np.arange("2016-07", "2016-08", dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [37]:
a = np.ones(3) * 1
b = np.ones(3) * 2

np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a, out=a)
np.multiply(b, a)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [38]:
a = np.random.uniform(1,5,5)
print(a)
print(a - a%1)
print(a//1)
print(a.astype(int))
print(np.floor_divide(a,1))

[4.72013033 3.85200064 3.34420334 1.06504461 4.83017412]
[4. 3. 3. 1. 4.]
[4. 3. 3. 1. 4.]
[4 3 3 1 4]
[4. 3. 3. 1. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [39]:
a = np.arange(5)
np.tile(a,(4,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [40]:
def abc():
    for i in range(10):
        yield i
        
np.fromiter(abc(), dtype=float, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [41]:
np.linspace(0,1,11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [42]:
a = np.random.randint(1,10,10)
np.sort(a)

array([3, 3, 5, 5, 6, 6, 7, 7, 8, 9])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [43]:
a = np.ones(100)
%timeit np.add.reduce(a)

%timeit np.sum(a)

%timeit sum(a)

545 ns ± 8.16 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.56 µs ± 23 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.52 µs ± 4.15 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [44]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)

#完全一致
print(np.all(a==b))

#多少の猶予あり一致
print(np.allclose(a,b))

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [45]:
a = np.arange(10)
a.flags.writeable = False
a[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
import matplotlib.pyplot as plt


z = np.random.random((10, 2))
x,y = z[:,0],z[:,1]

radii = np.sqrt(x**2 + y**2)
theta = np.arctan2(y,x)
    
# 極座標系グラフ
ax2 = plt.subplot(1,1,1,polar=True)
ax2.scatter(theta,radii)
ax2.set_rmax(1)
ax2.grid(True)

plt.show()

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
a = np.random.random(10)
a[np.argmax(a)] = 0
a

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
Z = np.zeros((5,5), [('x',float),('y',float)])
print(Z)

Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
x = np.arange(3)
y = x + 0.5

# cの行列を作成
c = 1.0/np.subtract.outer(x,y)

# cの行列式
np.linalg.det(c)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
    
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
import numpy

a = numpy.arange(10000)

# 全て表示する
# numpy.set_printoptions(threshold=float("inf"))

# デフォルト値に戻す
# numpy.set_printoptions(threshold=1000)

print(a)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [ ]:
a = np.arange(0, 100, 2)

b = np.random.uniform(0,100)

np.searchsorted(a, b)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [ ]:
z = np.zeros(10,[("position", [("x", float),
                               ("y", float)]),
                 ("color",    [("r", float),
                               ("g", float),
                               ("b", float)])])
z

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

In [ ]:
from scipy.spatial import distance

Z = np.random.random((10,2))
distance.cdist(Z,Z)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [ ]:
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)

Y = Z.view(np.int32)
print(Y)

Y[:] = Z
print(Y)

#理解が出来ない。 astpyeでいいのでは？

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO('''
             1, 2, 3, 4, 5
             6,  ,  , 7, 8
              ,  , 9,10,11
              ''')

np.genfromtxt(s, delimiter=",", dtype=int8)

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
Z = np.arange(9).reshape(3,3)
print(Z)

for index, value in np.ndenumerate(Z):
    print(index, value)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### ２次元ガウス配列(要学習）


$$確率密度関数	𝑓(𝑋)=\frac{1}{\sqrt2πσ^2}exp[−\frac{(𝑥−μ)^2}{2σ^2}]$$
$$期待値（平均）	𝐸(𝑋)=μ$$
$$分散	𝑉(𝑋)=σ^2$$
$$標準偏差	𝑆𝐷(𝑋)=σ$$

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)

sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

#### 57. How to randomly place p elements in a 2D array? (★★☆)
p要素を2D配列にランダムに配置するにはどうすればよいですか？

In [ ]:
n = 5
p = 2
z = np.zeros((n,n))

x = np.random.choice(range(n*n),p,replace=False)
print(x)

np.put(z, x, 1)
z

#### 58. Subtract the mean of each row of a matrix (★★☆)  
行列の各行の平均を減算します

In [ ]:
a = np.random.randint(0,10,(2,4))
print(a)

print(a - a.mean(axis=1,keepdims=True))

#### 59. How to sort an array by the nth column? (★★☆)  
n番目の列で配列を並べ替える方法は？

In [ ]:
a = np.random.randint(1,10,(3,3))
print(a)

print(a[a[:,1].argsort()])

#### 60. How to tell if a given 2D array has null columns? (★★☆)  
特定の2D配列にnull列があるかどうかを確認するにはどうすればよいですか？

In [ ]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

#### 61. Find the nearest value from a given value in an array (★★☆)  
配列内の指定された値から最も近い値を見つけます

In [ ]:
a = np.random.rand(3,3)
print(a)
z = np.random.rand(1)
print(z)

# np.absは絶対値をとる、一番差が小さいインデックスを抽出
index = np.abs(z - a).argmin()

# np.flatはイテレータを返す
a.flat[index]

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)  
形状が（1,3）と（3,1）の2つの配列を考えると、イテレーターを使用してそれらの合計を計算する方法は？

In [ ]:
# for以降、理解が出来ない

In [ ]:
A = np.arange(3).reshape(3,1)
print(A)
B = np.arange(3).reshape(1,3)
print(B)

it = np.nditer([A,B,None])
print(it)

for x,y,z in it: z[...] = x + y
print(it.operands[2])

#### 63. Create an array class that has a name attribute (★★☆)  
name属性を持つ配列クラスを作成します

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10),"range_10")
print (Z.name)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)  
与えられたベクトルを考えてみましょう。2番目のベクトルでインデックス付けされた各要素に1を追加する方法（インデックスの繰り返しに注意してください）？

In [ ]:
z = np.ones(10)
print(z)
i = np.random.randint(0,len(z), 20)
print(i)
z += np.bincount(i, minlength=len(z))
print(z)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)  
インデックスリスト（I）に基づいて、ベクトル（X）の要素を配列（F）に累積する方法は？

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)
（dtype = ubyte）の（w、h、3）画像を考慮して、一意の色の数を計算します

#理解不能

In [46]:
w,h = 16,16
i = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
f = i[...,0]*256*256 + i[...,1]*256 + i[...,2]
n = len(np.unique(f))
print(np.unique(i))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)
4次元配列を考えると、最後の2つの軸の合計を一度に取得するにはどうすればよいですか？

In [47]:
a = np.random.randint(0,4,(2,2,2,2))
print(a)

a.sum(axis=(-1,-2))

[[[[2 3]
   [2 1]]

  [[1 0]
   [0 1]]]


 [[[2 2]
   [0 3]]

  [[2 1]
   [3 2]]]]


array([[8, 2],
       [7, 8]])

In [48]:
random.seed(0)
A = np.random.randint(0,5,(2,2,2,2))
print(A)
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-1,-2))
print("合計\n",sum)

[[[[4 0]
   [3 3]]

  [[3 1]
   [3 2]]]


 [[[4 0]
   [0 4]]

  [[2 1]
   [0 1]]]]
合計
 [[10  9]
 [ 8  4]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)  
1次元のベクトルDを考えると、サブセットインデックスを記述する同じサイズのベクトルSを使用して、Dのサブセットの平均を計算する方法は？

In [49]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.58418375 0.5139626  0.36119673 0.4285821  0.43883858 0.51131167
 0.61261829 0.47608844 0.35346    0.50276739]


#### 69. How to get the diagonal of a dot product? (★★★)  
内積の対角線を取得するにはどうすればよいですか？

In [50]:
a = np.random.randint(0,3,(2,2))
b = np.random.randint(0,3,(2,2))
print(a)
print(b)
c = a@b
print(c)
print(np.diag(c))

[[1 0]
 [1 2]]
[[1 1]
 [0 0]]
[[1 1]
 [1 1]]
[1 1]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)
ベクトル[1、2、3、4、5]について考えてみましょう。各値の間に、3つの連続するゼロがインターリーブされた新しいベクトルを作成する方法を教えてください。

In [51]:
a = [1, 2, 3, 4, 5]
nz = 3
z0 = np.zeros(len(a) + (len(a)-1)*(nz))
print(z0)
z0[::nz+1] = a
print(z0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)
次元（5,5,3）の配列を考えてみましょう。次元（5,5）の配列でそれを多重化する方法は？

In [52]:
A = np.ones((5,5,3))
print(A)
B = 2*np.ones((5,5))
print(B)
print(B[:,:,None])
print(A * B[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]

 [[2.]
  [2.]
  [2.]
  [2.]
  [2.]]]
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)
配列の2つの行を交換する方法は？

In [53]:
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)
（頂点が共有されている）10個の三角形を表す10個のトリプレットのセットを検討し、すべての三角形を構成する一意の線分のセットを見つけます。


In [54]:
# 理解不能
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 58) ( 0, 86) (17, 22) (17, 30) (18, 70) (18, 71) (21, 46) (21, 73)
 (22, 30) (28, 73) (28, 81) (39, 39) (39, 75) (41, 49) (41, 93) (43, 83)
 (43, 92) (46, 73) (49, 93) (58, 86) (66, 85) (66, 91) (70, 71) (73, 81)
 (83, 92) (85, 91) (89, 91) (89, 96) (91, 96)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
bincountに対応するソートされた配列Cが与えられた場合、np.bincount（A）== Cとなるような配列Aを生成するにはどうすればよいですか？

In [55]:
C = np.bincount([1,1,2,3,4,4,6])
print(C)


print(np.arange(len(C)))
# numpy.repeat(a, n) はスカラーや配列 a の各要素を n 回 繰り返す 配列を生成します。
A = np.repeat(np.arange(len(C)), C)
print(A)

[0 2 1 1 2 0 1]
[0 1 2 3 4 5 6]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)
配列上のスライディングウィンドウを使用して平均を計算するにはどうすればよいですか？


In [63]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    # np.cumsum()で累積和を取得
    ret = np.cumsum(a, dtype=float)
    print(ret)
    print(ret[n:])
    print(ret[:-n])
    # スライド幅 -1 の幅を算出（−１は重複している値)
    ret[n:] = ret[n:] - ret[:-n]
    print(ret[n:])
    print(ret[n - 1:])
    # 重複して削除された値を補填して平均化
    return ret[n - 1:] / n
Z = np.arange(5)
print(Z)
print(moving_average(Z, n=3))

[0 1 2 3 4]
[ 0.  1.  3.  6. 10.]
[ 6. 10.]
[0. 1.]
[6. 9.]
[3. 6. 9.]
[1. 2. 3.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
1次元配列Zを考え、最初の行が（Z [0]、Z [1]、Z [2]）で、後続の各行が1ずつシフトされる2次元配列を作成します（最後の行は（Z [ -3]、Z [-2]、Z [-1]）


In [67]:
from numpy.lib.stride_tricks import as_strided

def roll(a, window):
    # shapeサイズを求める>>>(8,3)
    shape = (a.size - window + 1, window)
    # stride_tricks.as_stridedの引数strides（スキップ幅)は、byte単位で計算するので、aのbyte数を抽出する。
    strides = (a.itemsize, a.itemsize)
    return as_strided(a, shape=shape, strides=strides)

roll(np.arange(10),3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)
ブール値を無効にする方法、またはフロートの符号をインプレースで変更する方法は？

In [73]:
# Author: Nathaniel J. Smith

#ブール値の無効（否定）
Z = np.random.randint(0,2,100)
z = np.logical_not(Z, out=Z)
print(Z)
print(z)

#インプレース
A = np.random.uniform(-1.0,1.0,100)
a = np.negative(Z, out=Z)
print(A)
print(a)

[0 0 0 1 1 0 1 1 0 1 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 0
 0 1 0 1 1 1 1 1 0 0 1 1 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0
 1 1 0 1 1 0 1 0 1 0 1 1 0 1 1 1 1 1 0 1 0 1 1 0 0 0]
[0 0 0 1 1 0 1 1 0 1 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 0
 0 1 0 1 1 1 1 1 0 0 1 1 1 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0
 1 1 0 1 1 0 1 0 1 0 1 1 0 1 1 1 1 1 0 1 0 1 1 0 0 0]
[-0.20100218 -0.39633825  0.55043955  0.85242586 -0.34937939  0.90574134
 -0.97210321  0.06693136 -0.39083594  0.76572    -0.49875456  0.35482366
  0.62084818 -0.1357039   0.50426904  0.6592045  -0.24193246 -0.80690078
 -0.48772085  0.18387032 -0.0470456  -0.02413086 -0.0829709   0.04918524
 -0.11596936  0.70526985 -0.13312205  0.65374074  0.01868413 -0.82724604
  0.32007972 -0.58681079  0.69455065  0.36271826 -0.6432653  -0.86028197
 -0.98062366  0.78409932 -0.73306958  0.55838395  0.85032685  0.4303575
 -0.01836277 -0.06100339  0.76541858 -0.02317988 -0.17086503 -0.6517761
 -0.049421

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)
線（2d）と点pを表す2組の点P0、P1を考えてみましょう。pから各線i（P0 [i]、P1 [i]）までの距離を計算する方法は？


点と直線の公式  
http://www.info.hiroshima-cu.ac.jp/~miyazaki/knowledge/tech0044.html

In [74]:
p = np.random.randint(-10,10,(1,2))
print(p)

P0 = np.random.randint(-10,10,(1,2))
P1 = np.random.randint(-10,10,(1,2))
print(P0, P1)

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    print(U)
    U = U.reshape(len(U),1)
    print(U)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

print(distance(P0, P1, p))

[[ 5 -7]]
[[ 4 -5]] [[1 9]]
[-0.15121951]
[[-0.15121951]]
[0.55874424]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)
線（2d）を表す2組の点P0、P1と1組の点Pを考えてみましょう。各点j（P [j]）から各線i（P0 [i]、P1 [i]）までの距離を計算する方法は？


In [75]:
p = np.random.randint(-10,10,(10,2))
print(p)

print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[-4 -4]
 [ 9 -4]
 [-8 -4]
 [-5 -5]
 [ 3 -1]
 [-6  3]
 [ 7 -7]
 [ 3  9]
 [-2  3]
 [-5  6]]
[0.18536585]
[[0.18536585]]
[-0.00487805]
[[-0.00487805]]
[0.24390244]
[[0.24390244]]
[0.13170732]
[[0.13170732]]
[0.28780488]
[[0.28780488]]
[0.69268293]
[[0.69268293]]
[-0.1804878]
[[-0.1804878]]
[0.97073171]
[[0.97073171]]
[0.63414634]
[[0.63414634]]
[0.88292683]
[[0.88292683]]
[[ 7.61289022]
 [ 5.09854116]
 [11.52409988]
 [ 8.80022173]
 [ 0.13968606]
 [ 8.10179143]
 [ 2.51434906]
 [ 1.95560483]
 [ 4.19058177]
 [ 6.49540175]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
任意の配列を検討し、固定された形状で特定の要素を中心とするサブパーツを抽出する関数を記述します（必要に応じて塗りつぶし値のあるパッド）

In [77]:
Z = np.random.randint(0,3,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R  = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 1 0 2 0 1 2 0 0 1]
 [1 0 2 1 2 1 2 0 2 0]
 [2 0 0 2 1 0 2 0 0 2]
 [0 1 2 0 2 2 1 2 2 2]
 [2 2 0 2 0 0 1 1 2 1]
 [0 2 1 0 1 2 1 2 2 1]
 [2 2 2 2 1 2 2 2 2 0]
 [1 1 0 1 0 1 1 2 0 0]
 [1 0 2 1 1 2 0 0 1 1]
 [2 0 0 0 2 2 1 1 1 1]]
[[0 0 0 0 0]
 [0 0 1 0 2]
 [0 1 0 2 1]
 [0 2 0 0 2]
 [0 0 1 2 0]]


<ipython-input-77-5859bd2b32fe>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
配列Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]を考えてみましょう。配列を生成する方法は、R = [[1,2,3、 4]、[2,3,4,5]、[3,4,5,6]、...、[11,12,13,14]]？

In [78]:
Z = np.arange(1,15,dtype=np.uint32)
R = as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)
行列の階数を計算する

In [84]:
a = np.random.randint(0,5,(16,4))
print(a)

np.linalg.matrix_rank(a)

[[2 3 2 2]
 [1 3 3 0]
 [4 3 3 0]
 [0 1 4 4]
 [1 0 0 0]
 [3 4 4 2]
 [2 3 3 4]
 [2 1 0 4]
 [1 3 0 3]
 [2 1 0 0]
 [3 4 1 0]
 [0 2 1 1]
 [0 1 1 0]
 [0 3 3 3]
 [3 1 2 0]
 [0 4 2 2]]


4

#### 83. How to find the most frequent value in an array?
配列内で最も頻度の高い値を見つける方法


In [92]:
a = np.random.randint(0,10,30)
print(a)

a[np.bincount(a).argmax()]

[5 0 5 8 9 8 2 5 3 1 7 3 8 5 5 1 9 7 2 1 0 1 0 1 1 6 8 8 3 2]


0

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
ランダムな10x10行列からすべての隣接する3x3ブロックを抽出します


In [98]:
Z = np.random.randint(0,5,(5,5))
print(Z)
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[1 4 0 2 3]
 [0 0 1 1 1]
 [2 1 0 1 4]
 [4 3 4 3 4]
 [2 3 4 3 3]]
[[[[1 4 0]
   [0 0 1]
   [2 1 0]]

  [[4 0 2]
   [0 1 1]
   [1 0 1]]

  [[0 2 3]
   [1 1 1]
   [0 1 4]]]


 [[[0 0 1]
   [2 1 0]
   [4 3 4]]

  [[0 1 1]
   [1 0 1]
   [3 4 3]]

  [[1 1 1]
   [0 1 4]
   [4 3 4]]]


 [[[2 1 0]
   [4 3 4]
   [2 3 4]]

  [[1 0 1]
   [3 4 3]
   [3 4 3]]

  [[0 1 4]
   [4 3 4]
   [4 3 3]]]]


#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
Z [i、j] == Z [j、i]となるような2D配列サブクラスを作成します

#スーパークラスの作り方とかよう勉強

In [116]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 9  0  6 15 13]
 [ 0  6  5 15 10]
 [ 6  5  1 42 11]
 [15 15 42  9 14]
 [13 10 11 14  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
形状（n、n）を持つp行列のセットと、形状（n、1）を持つpベクトルのセットについて考えてみます。 p行列積の合計を一度に計算する方法は？ （結果の形状は（n、1））

In [130]:
n = 2
p = np.random.randint(0,5,(2,n,n))
print(p)
print(p.shape)

b = np.random.randint(0,5,(2,n,1))
print(b)
print(b.shape)

np.tensordot(p, b, axes = [[0,2],[0,1]])

[[[1 1]
  [0 3]]

 [[3 4]
  [2 0]]]
(2, 2, 2)
[[[3]
  [1]]

 [[0]
  [0]]]
(2, 2, 1)


array([[4],
       [3]])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
16x16配列を考えてみましょう。ブロック合計（ブロックサイズは4x4）を取得する方法は？
参考URL  
https://qiita.com/nyandora/items/0fac6e307edc16c3cb91

In [131]:
answer(87)

# Author: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)


In [139]:
z = np.ones((16,16))
print(z)

k = 4
# reduceat(単一の軸上で指定されたスライスを使用して（ローカル）縮小を実行します。)
s1 = np.add.reduceat(z, np.arange(0, z.shape[0],k), axis=0)
print(s1)
s2 = np.add.reduceat(s1,np.arange(0, s1.shape[1],k), axis=1)

print(s2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4

#### 88. How to implement the Game of Life using numpy arrays? (★★★)
numpy配列を使用してGameof Lifeを実装するにはどうすればよいですか？  
Game of Lifeのwiki  
https://ja.wikipedia.org/wiki/%E3%83%A9%E3%82%A4%E3%83%95%E3%82%B2%E3%83%BC%E3%83%A0

In [200]:
#意味不明

In [199]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

a = np.random.randint(0,2,(5,5))
print(a)

for i in range(10): Z = iterate(a)
print(Z)

[[1 1 1 1 1]
 [1 0 0 1 1]
 [0 1 1 0 0]
 [0 1 1 0 1]
 [1 1 1 1 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)
配列のn個の最大値を取得する方法

In [203]:
a = np.random.randint(0,10,10)
print(a)

a.max()

[4 5 8 6 8 5 8 8 4 5]


8

In [206]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
%timeit Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[   0    1    2 ... 9997 9998 9999]
[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)